server:
  port: 8001 # 项目端口

spring:
  application:
    name: provider-server # 项目名称

dubbo: # dubbo配置
  application:
    name: provider-server # dubbo服务名称
  protocol:
    port: -1 # dubbo服务端口
    name: dubbo # dubbo服务协议名称
  registry: # dubbo使用的注册中心
    address: nacos://10.255.8.109:8848?register-consumer-url=true # dubbo注册中心地址
  scan:
    base-packages: com.sunyb.learn
