server:
  port: 8002 # 项目端口

spring:
  application:
    name: provider-consumer # 项目名称

dubbo: # dubbo配置
  application:
    name: provider-consumer # dubbo服务名称
  protocol:
    port: 20882 # dubbo服务端口
    name: dubbo # dubbo服务协议名称
  registry: # dubbo使用的注册中心
    address: nacos://10.255.8.109:8848?register-consumer-url=true # dubbo注册中心地址
  monitor:
    protocol: registry
  scan:
    base-packages: com.sunyb.learn
